### ISSUE TITLE
Планируете развивать? 

### ISSUE THREAD

**Issue by camorazrushimoe** [alexfromvl/vk-to-slack#1]
Было бы круто перенаправлять в отдельный канал в slack сообщения которые приходят в директ сообществу в вк.

**Comment by alexfromvl** [comment]
Надо посмотреть поддерживается ли такое поведение в API VK. Когда писал первую версию еще не было доступа по API к сообщениям сообществ. 
Посмотрим, появилась ли возможность сделать такое перенаправление и постараюсь обновить код.

**Comment by alexfromvl** [comment]
@camorazrushimoe Добавил messages_bot_slack.py
Там есть основная логика, которая требуется для реализации перенаправления сообщений vk в отдельный канал slack. Реализовано через longpoll. Когда полностью протестирую работу кода, обновлю файл.

**Comment by alexfromvl** [comment]
Код протестирован и обновлен. Смотреть файл messages_bot_slack.py

Работает простая отправка и автоматический ответ на сообщение. Дальше можно дорабатывать по желанию, используя стандартное API.
